### ISSUE TITLE
Error codes

### ISSUE THREAD

**Issue by zacbri** [hamishforbes/lua-resty-consul#8]
Hi,

it would be useful to also return a status code in case of an error, (maybe the original HTTP status) to be able to trigger different behaviour in the client code without having to parse the error message.

Let me know if you'd like me to try and have a go at it.

Thanks

**Comment by AlecHFerguson** [comment]
I would like this feature. Does Looking at function `_get` it looks like any non-200 status code returns an error:

```
elseif status ~= 200 then
  if status == 404 then
    return nil, "Key not found"
  else
    return nil, "Consul returned: HTTP "..status
  end
end
```

So as a workaround you should be able to parse the status code from the error message.

Adding the status code explicitly would be a breaking change since the return type would probably need to be a table. I'm quite new to Lua but maybe something like this?

```
return nil, { message = "Consul returned: HTTP "..status, status = res.status }
```

**Comment by hamishforbes** [comment]
Closing in favour of #18
